name: Publish Packages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: ['personal', 'article-social-cards']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - name: build example/${{ matrix.example }}
        working-directory: examples/${{ matrix.example }}
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: yarn build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits 
          fetch-depth: 0
      - run: yarn
      - name: create release pull request
        uses: changesets/action@master
        with:
          publish: yarn publish-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
